/**
 * Public employer feedback form — /feedback?token=<feedbackToken>
 *
 * Flow:
 * 1. Employer receives a link (generated by Rachel via StudentEditor → "קישור משוב מעסיק")
 * 2. They open the URL, which includes a unique feedbackToken in the query string
 * 3. This page finds the matching student by scanning practicum_data
 * 4. Employer fills out: overall rating (1–5), free text, hired checkbox
 * 5. On submit:
 *    - Updates student.feedbackText, student.hired, student.feedbackSubmittedAt
 *    - Sends coordinator email via mailto: (fallback — no server needed)
 *    - Shows success message
 */

import { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { saveSnapshot } from '../lib/dataApi';
import type { Student, PracticumData } from '../lib/supabase';

type Phase = 'loading' | 'not-found' | 'already-done' | 'form' | 'submitting' | 'done' | 'error';

export default function EmployerFeedback() {
  const [phase, setPhase] = useState<Phase>('loading');
  const [student, setStudent] = useState<Student | null>(null);
  const [allData, setAllData] = useState<PracticumData | null>(null);
  const [rating, setRating] = useState(0);
  const [feedbackText, setFeedbackText] = useState('');
  const [hired, setHired] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  const token = typeof window !== 'undefined'
    ? new URLSearchParams(window.location.search).get('token') || ''
    : '';

  useEffect(() => {
    if (!token) { setPhase('not-found'); return; }
    load();
  }, [token]);

  async function load() {
    setPhase('loading');
    const { data: row, error } = await supabase
      .from('practicum_data')
      .select('data')
      .eq('org_id', 'default')
      .single();
    if (error || !row) { setPhase('not-found'); return; }
    const d = (row as any).data as PracticumData;
    const found = (d.students || []).find(s => s.feedbackToken === token);
    if (!found) { setPhase('not-found'); return; }
    if (found.feedbackSubmittedAt) { setPhase('already-done'); setStudent(found); return; }
    setStudent(found);
    setAllData(d);
    setPhase('form');
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!student || !allData) return;
    if (rating === 0) { alert('אנא בחר דירוג (1–5)'); return; }
    setPhase('submitting');
    const now = new Date().toISOString();
    const updatedStudent: Student = {
      ...student,
      feedbackText: feedbackText.trim() || student.feedbackText || '',
      hired,
      feedbackSubmittedAt: now,
    };
    const nextStudents = (allData.students || []).map(s =>
      s.id === student.id ? updatedStudent : s
    );
    const res = await saveSnapshot(
      { ...allData, students: nextStudents },
      { name: 'מעסיק (משוב)' },
      { action: 'משוב מעסיק התקבל', entity: 'סטודנט', target: student.name }
    );
    if (!res.ok) {
      setErrorMsg(res.error || 'שגיאה בשמירה');
      setPhase('error');
      return;
    }
    // Try to send coordinator a copy via mailto (client-side only — no server needed)
    const coordEmail = 'rachel@ariel.ac.il'; // fallback; could be configured
    try {
      const subj = encodeURIComponent(`משוב מעסיק — ${student.name}`);
      const body = encodeURIComponent(
        `שלום,\n\n` +
        `המעסיק מילא משוב עבור: ${student.name}\n` +
        `ארגון: ${student.acceptedOrg || ''}\n` +
        `דירוג: ${'⭐'.repeat(rating)}\n` +
        `נקלט/ה לעבודה: ${hired ? 'כן' : 'לא'}\n` +
        (feedbackText ? `\nתוכן המשוב:\n${feedbackText}\n` : '') +
        `\nתאריך: ${new Date(now).toLocaleString('he-IL')}`
      );
      // open silently — if blocked by browser, user still sees success
      window.open(`mailto:${coordEmail}?subject=${subj}&body=${body}`, '_blank');
    } catch (_) { /* silent */ }
    setPhase('done');
  }

  const stars = [1, 2, 3, 4, 5];

  if (phase === 'loading') return <PageShell><Spinner /></PageShell>;

  if (phase === 'not-found') return (
    <PageShell>
      <div className="text-center py-16">
        <div className="serif text-[32px] mb-3" style={{ color: 'var(--ink)' }}>הקישור אינו תקין</div>
        <div className="text-[15px]" style={{ color: 'var(--text-soft)' }}>ייתכן שהקישור פג תוקף או שגוי. פנה/י לרכזת הפרקטיקום.</div>
      </div>
    </PageShell>
  );

  if (phase === 'already-done') return (
    <PageShell>
      <div className="text-center py-16">
        <div className="text-[48px] mb-4">✅</div>
        <div className="serif text-[28px] mb-2" style={{ color: 'var(--ink)' }}>המשוב כבר התקבל</div>
        <div className="text-[15px]" style={{ color: 'var(--text-soft)' }}>
          המשוב עבור {student?.name} נשלח בתאריך{' '}
          {student?.feedbackSubmittedAt ? new Date(student.feedbackSubmittedAt).toLocaleDateString('he-IL') : ''}.
        </div>
      </div>
    </PageShell>
  );

  if (phase === 'done') return (
    <PageShell>
      <div className="text-center py-16">
        <div className="text-[48px] mb-4">🙏</div>
        <div className="serif text-[32px] mb-3" style={{ color: 'var(--ink)' }}>תודה על המשוב!</div>
        <div className="text-[15px]" style={{ color: 'var(--text-soft)' }}>
          המשוב עבור {student?.name} נשמר בהצלחה ורכזת הפרקטיקום קיבלה עותק.
        </div>
      </div>
    </PageShell>
  );

  if (phase === 'error') return (
    <PageShell>
      <div className="text-center py-16">
        <div className="serif text-[28px] mb-3" style={{ color: 'var(--ink)' }}>שגיאה בשמירת המשוב</div>
        <div className="text-[15px]" style={{ color: 'var(--text-soft)' }}>{errorMsg}</div>
        <button onClick={load} className="btn btn-primary mt-6">נסה שוב</button>
      </div>
    </PageShell>
  );

  return (
    <PageShell>
      <div className="max-w-[560px] mx-auto">
        <div className="chapter-mark mb-4">פרקטיקום · משוב מעסיק</div>
        <h1 className="serif text-[34px] leading-[1.1] mb-2" style={{ color: 'var(--ink)' }}>
          משוב על {student?.name}
        </h1>
        {student?.acceptedOrg && (
          <div className="text-[15px] mb-8" style={{ color: 'var(--text-soft)' }}>
            ארגון: {student.acceptedOrg}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-7">
          {/* Star rating */}
          <div>
            <label className="mono text-[11px] uppercase tracking-[0.16em] font-semibold block mb-3" style={{ color: 'var(--text-soft)' }}>
              דירוג כללי *
            </label>
            <div className="flex gap-2 flex-row-reverse justify-end" dir="ltr">
              {stars.map(n => (
                <button
                  key={n}
                  type="button"
                  onClick={() => setRating(n)}
                  className="text-[32px] transition-all duration-100 hover:scale-110 focus:outline-none"
                  style={{ opacity: n <= rating ? 1 : 0.25, lineHeight: 1 }}
                  aria-label={`${n} כוכבים`}
                >
                  ⭐
                </button>
              ))}
            </div>
            {rating > 0 && (
              <div className="mono text-[11px] uppercase tracking-[0.14em] mt-2" style={{ color: 'var(--accent)' }}>
                {['', 'לא מרוצה', 'מרוצה חלקית', 'בינוני', 'טוב', 'מצוין'][rating]}
              </div>
            )}
          </div>

          {/* Free text */}
          <div>
            <label className="mono text-[11px] uppercase tracking-[0.16em] font-semibold block mb-2" style={{ color: 'var(--text-soft)' }}>
              חוות דעת (אופציונלי)
            </label>
            <textarea
              value={feedbackText}
              onChange={e => setFeedbackText(e.target.value)}
              rows={5}
              placeholder="תאר/י את חוות דעתך על הסטודנט/ית — יכולות מקצועיות, יחסי אנוש, מוטיבציה..."
              className="input w-full"
              style={{ padding: '12px 16px', fontSize: '14.5px', resize: 'vertical' }}
            />
          </div>

          {/* Hired checkbox */}
          <label className="inline-flex items-center gap-3 cursor-pointer py-2">
            <input
              type="checkbox"
              checked={hired}
              onChange={e => setHired(e.target.checked)}
              className="w-4 h-4"
              style={{ accentColor: 'var(--accent)' }}
            />
            <span className="text-[15px]" style={{ color: 'var(--ink)' }}>
              הסטודנט/ית נקלט/ה לעבודה בארגוננו בסיום הפרקטיקום
            </span>
          </label>

          <button
            type="submit"
            disabled={phase === 'submitting' || rating === 0}
            className="btn btn-primary w-full"
            style={{ padding: '14px 0', fontSize: '16px' }}
          >
            {phase === 'submitting' ? 'שולח...' : 'שלח משוב →'}
          </button>
        </form>
      </div>
    </PageShell>
  );
}

function PageShell({ children }: { children: React.ReactNode }) {
  return (
    <main className="max-w-[720px] mx-auto px-6 pt-14 pb-28 min-h-screen">
      {children}
    </main>
  );
}

function Spinner() {
  return (
    <div className="flex items-center justify-center py-24 gap-3">
      <span style={{ fontSize: '22px', animation: 'practicum-spin 0.7s linear infinite', display: 'inline-block' }}>↻</span>
      <span className="mono text-[12px] uppercase tracking-[0.14em]" style={{ color: 'var(--text-soft)' }}>טוען...</span>
    </div>
  );
}
